version: "3"

services:
  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - salimsolutions-net

  certbot:
    container_name: certbot
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    networks: 
      - default
      - salimsolutions-net


networks:
  salimsolutions-net:
    driver: bridge
    name: salimsolutions-net
    external: true